# 
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Dependency Plugin"
  homepage: https://maven.apache.org/plugins/maven-dependency-plugin/
  labels:
    - java
    - build-management
    - maven-plugins
    - maven-dependency-plugin
    - maven
    - hacktoberfest
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  protected_branches:
    master: {}
  pull_requests:
    del_branch_on_merge: true
  features:
    issues: true
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org

# https://releases.apache.org/projects/maven-dependency-plugin

project:
  metadata:
    key: maven-dependency-plugin
    committee: maven
    name: Apache Maven Dependency Plugin
    description: Provides utility goals to work with dependencies like copying, unpacking,
      analyzing, resolving and many more.
    homepage: https://maven.apache.org/plugins/maven-dependency-plugin/
    download_page: https://maven.apache.org/plugins/maven-dependency-plugin/download.cgi
    bug_database: https://github.com/apache/maven-dependency-plugin/issues
    mailing_lists: https://maven.apache.org/plugins/maven-dependency-plugin/mailing-lists.html
    repositories:
      - https://github.com/apache/maven-dependency-plugin
    categories:
      - build-management
    programming_languages:
      - Java
  policy:
    announce_release_template_url: https://maven.apache.org/atr/templates/announce_release_template.txt
    start_vote_template_url: https://maven.apache.org/atr/templates/start_vote_template.txt
    finish_vote_template_url: https://maven.apache.org/atr/templates/finish_vote_template.txt
    github_repository_name: maven-dependency-plugin
    download_path_suffix: plugins
    vote_recipients:
      to: dev@maven.apache.org
    announce_recipients:
      to: announce@maven.apache.org
      cc:
        - dev@maven.apache.org
        - user@maven.apache.org
  features:
    atr_sync: true
