# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

invoker.goals.1 = ${project.groupId}:${project.artifactId}:${project.version}:tree -DoutputFile=auto.txt
invoker.goals.2 = ${project.groupId}:${project.artifactId}:${project.version}:tree -Dtokens=extended -DoutputFile=extended.txt -DoutputEncoding=UTF-8
invoker.goals.3 = ${project.groupId}:${project.artifactId}:${project.version}:tree -Dtokens=whitespace -DoutputFile=whitespace.txt
invoker.goals.4 = ${project.groupId}:${project.artifactId}:${project.version}:tree -Dtokens=standard -DoutputFile=standard.txt
invoker.goals.5 = ${project.groupId}:${project.artifactId}:${project.version}:tree -Dtokens=invalid -DoutputFile=invalid.txt
invoker.goals.6 = ${project.groupId}:${project.artifactId}:${project.version}:tree -l tree.log -Dstyle.color=always
